
networks:
  sb_net:
    driver: bridge

services:
  
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - sb_net
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
  
  spark-master:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - sb_net
    volumes:
      - ./data:/home/jovyan/work

  spark-worker-1:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
    networks:
      - sb_net
    volumes:
      - ./data:/home/jovyan/work
    depends_on:
      - spark-master

  spark-worker-2:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
    networks:
      - sb_net
    volumes:
      - ./data:/home/jovyan/work
    depends_on:
      - spark-master
  
  pyspark:
    build: .
    container_name: pyspark
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages org.apache.hadoop:hadoop-aws:3.3.4,io.delta:delta-spark_2.12:3.3.1 pyspark-shell
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 9999:8888
      - 4040:4040
    volumes:
      - .:/home/jovyan/work
    networks:
      - sb_net